name: X-Prison
version: 1.12.16
main: dev.drawethree.xprison.XPrison
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
authors: [ WildInterloper, Drawethree ]
api-version: 1.20
load: POSTWORLD
website: www.WildInterloper.com
