name: X-Prison
version: 1.14.0
main: dev.passarelli.xprison.XPrison
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
authors: [ WildInterloper, Drawethree, Ale1x ]
api-version: 1.20
load: POSTWORLD
website: passarelli.dev
